### ISSUE TITLE
The file with 'filename' does not exist, or is not an SBML string

### ISSUE THREAD

**Issue by AnisMansouri** [tamascogustavo/chimera#4]
Hi Everybody,

I tried to run the test command `python chimera_core.py core --organism e_coli_test.faa --type gramneg --media M9`, in the following folder `anaconda3/lib/python3.9/site-packages/ChiMera`, and I got the following error:

`$ python chimera_core.py core --organism e_coli_test.faa --type gramneg --media M9`
---------------------------------------------------
Building Model
---------------------------------------------------
  File "/home/anis/anaconda3/bin/diamond", line 113
    print "Diamond version %s" % (get_diamond_version())
          ^
SyntaxError: invalid syntax
Failed to run diamond.
Exit status: 0
e_coli_test.sbml SBML model was created
Traceback (most recent call last):
  File "/home/anis/anaconda3/lib/python3.9/site-packages/ChiMera/chimera_core.py", line 794, in <module>
    main()
  File "/home/anis/anaconda3/lib/python3.9/site-packages/ChiMera/chimera_core.py", line 774, in main
    execute_module(options)
  File "/home/anis/anaconda3/lib/python3.9/site-packages/ChiMera/chimera_core.py", line 102, in run_core_module
    model = read_model(model_name)
  File "/home/anis/anaconda3/lib/python3.9/site-packages/ChiMera/chimera_core.py", line 485, in read_model
    model = cobra.io.read_sbml_model(data, f_replace={})
  File "/home/anis/anaconda3/lib/python3.9/site-packages/cobra/io/sbml.py", line 252, in read_sbml_model
    raise e
  File "/home/anis/anaconda3/lib/python3.9/site-packages/cobra/io/sbml.py", line 249, in read_sbml_model
    doc = _get_doc_from_filename(filename)
  File "/home/anis/anaconda3/lib/python3.9/site-packages/cobra/io/sbml.py", line 292, in _get_doc_from_filename
    raise IOError(
OSError: [Errno The file with 'filename' does not exist, or is not an SBML string. Provide the path to an existing SBML file or a valid SBML string representation: 
%s] e_coli_test.sbml

Is it because of diamond or something else?

Thank you for any clarification,

**Comment by AnisMansouri** [comment]
After updating diamond (0.9.19) I got this error message:

`Database was built with a different version of Diamond and is incompatible`

**Comment by tamascogustavo** [comment]
Hey Anis, this is a problem with CarveMe.
This issue is happening to some users. We are trying to identify the problem.

As soon as we have any news, I will update this issue.

Best, 
Tamasco

**Comment by tamascogustavo** [comment]
Hey, I managed to fix the issue.

I just uninstalled diamond and re-installed it via conda.

This is are the programs for the fresh installation of the tool: 

```
name: model_builder
channels:
 - bioconda
 - defaults
dependencies:
 - _libgcc_mutex=0.1=main
 - _openmp_mutex=5.1=1_gnu
 - ca-certificates=2022.07.19=h06a4308_0
 - certifi=2022.6.15=py37h06a4308_0
 - diamond=0.9.14=h2e03b76_4
 - ld_impl_linux-64=2.38=h1181459_1
 - libffi=3.3=he6710b0_2
 - libgcc-ng=11.2.0=h1234567_1
 - libgomp=11.2.0=h1234567_1
 - libstdcxx-ng=11.2.0=h1234567_1
 - ncurses=6.3=h5eee18b_3
 - openssl=1.1.1q=h7f8727e_0
 - pip=22.1.2=py37h06a4308_0
 - python=3.7.13=h12debd9_0
 - readline=8.1.2=h7f8727e_1
 - setuptools=61.2.0=py37h06a4308_0
 - sqlite=3.39.0=h5082296_0
 - tk=8.6.12=h1ccaba5_0
 - wheel=0.37.1=pyhd3eb1b0_0
 - xz=5.2.5=h7f8727e_1
 - zlib=1.2.12=h7f8727e_2
 - pip:
  - aiosignal==1.2.0
  - anyio==3.6.1
  - appdirs==1.4.4
  - argon2-cffi==21.3.0
  - argon2-cffi-bindings==21.2.0
  - argparse==1.4.0
  - atomicwrites==1.4.1
  - attrs==22.1.0
  - backcall==0.2.0
  - beautifulsoup4==4.11.1
  - bleach==5.0.1
  - bs4==0.0.1
  - carveme==1.5.1
  - cffi==1.15.1
  - charset-normalizer==2.1.0
  - chimera-modelbuilder==2.0.15
  - click==8.0.4
  - cobra==0.22.1
  - commonmark==0.9.1
  - configobj==5.0.6
  - cplex==22.1.0.0
  - cycler==0.11.0
  - debugpy==1.6.2
  - decorator==5.1.1
  - defusedxml==0.7.1
  - depinfo==2.1.1
  - diskcache==5.4.0
  - distlib==0.3.5
  - entrypoints==0.4
  - escher==1.7.3
  - fastjsonschema==2.16.1
  - filelock==3.7.1
  - fonttools==4.34.4
  - frozenlist==1.3.1
  - future==0.18.2
  - grpcio==1.43.0
  - h11==0.12.0
  - httpcore==0.15.0
  - httpx==0.23.0
  - idna==3.3
  - importlib-metadata==4.12.0
  - importlib-resources==5.9.0
  - ipykernel==6.15.1
  - ipython==7.34.0
  - ipython-genutils==0.2.0
  - ipywidgets==7.7.1
  - jedi==0.18.1
  - jinja2==2.11.3
  - jsonschema==3.2.0
  - jupyter-client==7.3.4
  - jupyter-core==4.11.1
  - jupyterlab-pygments==0.2.2
  - jupyterlab-widgets==1.1.1
  - kiwisolver==1.4.4
  - markupsafe==2.0.1
  - matplotlib==3.5.2
  - matplotlib-inline==0.1.3
  - mistune==0.8.4
  - more-itertools==8.13.0
  - mpmath==1.2.1
  - msgpack==1.0.4
  - nbclient==0.5.13
  - nbconvert==6.4.5
  - nbformat==5.4.0
  - nest-asyncio==1.5.5
  - notebook==6.4.12
  - numpy==1.21.6
  - optlang==1.5.2
  - packaging==21.3
  - pandas==1.3.5
  - pandocfilters==1.5.0
  - parso==0.8.3
  - patsy==0.5.2
  - pexpect==4.8.0
  - pickleshare==0.7.5
  - pillow==9.2.0
  - platformdirs==2.5.2
  - plotly==5.9.0
  - plotly-express==0.4.1
  - pluggy==0.13.1
  - prometheus-client==0.14.1
  - prompt-toolkit==3.0.30
  - protobuf==3.20.1
  - psamm==1.1.2
  - psutil==5.9.1
  - ptyprocess==0.7.0
  - py==1.11.0
  - pycparser==2.21
  - pydantic==1.9.1
  - pygments==2.12.0
  - pyparsing==3.0.9
  - pyrsistent==0.18.1
  - pytest==4.6.11
  - python-dateutil==2.8.2
  - python-libsbml==5.19.0
  - pytz==2022.1
  - pyyaml==6.0
  - pyzmq==23.2.0
  - ray==1.13.0
  - reframed==1.2.1
  - requests==2.28.1
  - rfc3986==1.5.0
  - rich==12.5.1
  - ruamel-yaml==0.17.21
  - ruamel-yaml-clib==0.2.6
  - scipy==1.7.3
  - seaborn==0.11.2
  - send2trash==1.8.0
  - six==1.16.0
  - sniffio==1.2.0
  - soupsieve==2.3.2.post1
  - statsmodels==0.13.2
  - swiglpk==5.0.5
  - sympy==1.10.1
  - tenacity==8.0.1
  - terminado==0.15.0
  - testpath==0.6.0
  - tornado==6.2
  - traitlets==5.3.0
  - typing-extensions==4.3.0
  - urllib3==1.26.11
  - virtualenv==20.16.2
  - wcwidth==0.2.5
  - webencodings==0.5.1
  - widgetsnbextension==3.6.1
  - xlsxwriter==3.0.3
  - zipp==3.8.1
```

If you keep facing this issue, try to reinstall carveme as well.

**Comment by AnisMansouri** [comment]
Hi Gustavo,

Uninstalling and re-installing diamond via conda solved the problem.

Thank you!
