### ISSUE TITLE
Question about gram stain type

### ISSUE THREAD

**Issue by EmmettPeng** [tamascogustavo/chimera#5]
Hello thanks for developing this great tool for metabolic model analysis!

In your workflow, I notice that gram stain type parameter must be passed. I wonder what role it plays in modelling. What if the gram type is undetermined or the strain I provide is classified as archaea?

Any of your reply will be appreciated!

Emmett

**Comment by tamascogustavo** [comment]
Hi Emmett !Hi Emmett!
The tool uses CarveMe in the reconstruction module, which means that many of the functions are based on their structure.

The type of gram (+ or -) plays a role in the definition of the BOF (Biomass Objective Function), which describes the growth requirements of a cell. And is needed to perform the reconstruction using Contrait Based strategies.

If your organism is not classified but is a bacteria, you could try the bacteria type.

If archaea or an specific bacteria, you could also try to use CarveMe directly to build your model with a custom target function.

Here is a link showing how to build custom BOFs: https://carveme.readthedocs.io/en/latest/advanced.html#alternative-universes

After the SBML model is built, you can use ChiMera to finish your analysis.
