### ISSUE TITLE
JSON maps for P. putida and B. subtilis

### ISSUE THREAD

**Issue by dalbabur** [tamascogustavo/chimera#6]
Do you guys have JSON files already made for the P. putida and B. subtilis models? I've only been able to find the one available from Escher.

**Comment by tamascogustavo** [comment]
Hi @dalbabur, we use modified versions of the maps found on Escher. You can find all the maps here in the github, under dependencies. 

If you want more info on organism specific maps, check Escher gitter group: 
https://app.gitter.im/#/room/#zakandrewking_escher:gitter.im

Hope it helps.
